spring:
  application:
    name: marketplace
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_marketplace
    username: postgres
    password: DFzkdfhgh_2pm05bmn64
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true